Multigroup.Portal/Controllers/Administration/EarningsAllocationController.cs
using Multigroup.Common.Logging;
using Multigroup.Portal.Filters;
using Multigroup.Portal.Models.Administration;
using Multigroup.Services.Shared;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Multigroup.Portal.Helpers;
using Multigroup.DomainModel.Shared;
using Multigroup.Portal.Models.Maintenance;
using Multigroup.Portal.Utilities;
using Multigroup.Portal.Providers;
using System.Web.UI.WebControls;

namespace Multigroup.Portal.Controllers.Administration
{
    public class EarningsAllocationController : Controller
    {
        private EarningsAllocationService _earningsAllocationService;
        private IAuditLogHelper _auditLogHelper;
        private UserTypeService _userTypeService;
        private UserService _userService;
        private ProfileProvider _profileProvider;
        private CustomerService _customerService;
        private PartnerService _partnerService;

        public EarningsAllocationController()
        {
            _earningsAllocationService = new EarningsAllocationService();
            _auditLogHelper = new AuditLogHelper();
            _userTypeService = new UserTypeService();
            _userService = new UserService();
            _profileProvider = new ProfileProvider();
            _customerService = new CustomerService();
            _partnerService = new PartnerService();
        }

        // GET: /EarningsAllocation/
        [LogActionFilter]
        [Description("EarningsAllocations")]
        public ActionResult Index()
        {
            EarningsAllocationFilterVm model = new EarningsAllocationFilterVm();
            var collections = new CollectionHelper();
            model.ListUser = new SelectList(_userService.GetUsersComplete(), "UserId", "Names");
            return PartialView("~/Views/EarningsAllocation/EarningsAllocation.cshtml", model);
        }
        public ActionResult GetTable(int? SelectedUser, string DateFrom, string DateTo, string AmountFrom, string AmountTo)
        {
            var model = EarningsAllocationTableVm.ToViewModel(_earningsAllocationService.GetEarningsAllocationSummary(SelectedUser, DateFrom, DateTo, AmountFrom, AmountTo));
            return PartialView("~/Views/EarningsAllocation/EarningsAllocationTable.cshtml", model);
        }

        public ActionResult IndexPartners()
        {
            EarningsAllocationVm model = (EarningsAllocationVm)Session["SessionEarningsAllocation"];
            ViewBag.ErrorMessageTrabajo = "false";
            return PartialView("~/Views/EarningsAllocation/PartnersTable.cshtml", model);
        }

        [LogActionFilter]
        [Description("Crear EarningsAllocations")]
        public ActionResult Create()
        {
            var model = new EarningsAllocationVm();
            var collections = new CollectionHelper();
            List<EarningsAllocationPartner> lists = new List<EarningsAllocationPartner>();
            model.Partners = lists;
            model.Date = DateTime.Now.ToShortDateString();
            Session["SessionEarningsAllocation"] = model;
            return PartialView("~/Views/EarningsAllocation/EarningsAllocationCreate.cshtml", model);
        }

        [HttpPost]
        public ActionResult Create(EarningsAllocationVm model)
        {
            try
            {

                if (!ModelState.IsValid)
                {
                    var message = string.Join(" | ", ModelState.Values
                   .SelectMany(v => v.Errors)
                   .Select(e => e.ErrorMessage));

                    return new HttpStatusCodeResult(HttpStatusCode.InternalServerError, message);
                }
                if (model.Amount <= 0)
                    return new HttpStatusCodeResult(HttpStatusCode.InternalServerError, "El monto debe ser mayor a 0");

                EarningsAllocationVm principal = (EarningsAllocationVm)Session["SessionEarningsAllocation"];
                model.Partners = principal.Partners;
                double total = 0;
                foreach (EarningsAllocationPartner part in model.Partners)
                {
                    total = total + part.Amount;
                }

                if (Math.Abs((model.Amount - total)) >= 0.1)
                    return new HttpStatusCodeResult(HttpStatusCode.InternalServerError, "Error al calcular los totales de cada socio. Por favor recalcular");
                
                var earningsAllocation = model.ToModelObject();
                earningsAllocation.SystemDate = DateTime.Now;
                earningsAllocation.UserId = _profileProvider.CurrentUserId;

                _earningsAllocationService.AddEarningsAllocation(earningsAllocation);

                return Index();
            }
            catch (Exception ex)
            {

                return new HttpStatusCodeResult(HttpStatusCode.InternalServerError, "Se produjo un error al intentar guardar los datos.");
            }
        }

        public ActionResult View(int id)
        {
            var entity = _earningsAllocationService.GetEarningsAllocationsById(id);
            var model = EarningsAllocationVm.FromDomainModel(entity);

            return PartialView("~/Views/EarningsAllocation/EarningsAllocationView.cshtml", model);
        }

        public ActionResult Edit(int id)
        {
            var entity = _earningsAllocationService.GetEarningsAllocationsById(id);
            var model = EarningsAllocationVm.FromDomainModel(entity);

            Session["SessionEarningsAllocation"] = model;
            return PartialView("~/Views/EarningsAllocation/EarningsAllocationEdit.cshtml", model);
        }

        [HttpPost]
        public ActionResult Edit(EarningsAllocationVm model)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    var message = string.Join(" | ", ModelState.Values
                    .SelectMany(v => v.Errors)
                    .Select(e => e.ErrorMessage));

                    return new HttpStatusCodeResult(HttpStatusCode.InternalServerError, message);
                }

                if (model.Amount <= 0)
                    return new HttpStatusCodeResult(HttpStatusCode.InternalServerError, "El monto debe ser mayor a 0");

                EarningsAllocationVm principal = (EarningsAllocationVm)Session["SessionEarningsAllocation"];
                model.Partners = principal.Partners;
                double total = 0;
                foreach (EarningsAllocationPartner part in model.Partners)
                {
                    total = total + part.Amount;
                }

                if (Math.Abs((model.Amount - total)) >= 0.1)
                    return new HttpStatusCodeResult(HttpStatusCode.InternalServerError, "Error al calcular los totales de cada socio. Por favor recalcular");

                EarningsAllocation earningsAllocation = model.ToModelObject();
                earningsAllocation.SystemDate = DateTime.Now;
                earningsAllocation.UserId = _profileProvider.CurrentUserId;
                _earningsAllocationService.UpdateEarningsAllocation(earningsAllocation);
                return Index();
            }
            catch (Exception ex)
            {
                var log = new AuditLog()
                {
                    LogLevel = AuditLogLevel.Error,
                    Description = ex.Message,
                    InputParam = model,
                };
                _auditLogHelper.LogAuditFail(log);

                return new HttpStatusCodeResult(HttpStatusCode.InternalServerError, "Error al guardar");
            }
        }

        public ActionResult Partners(double amount)
        {
            EarningsAllocationVm principal = (EarningsAllocationVm)Session["SessionEarningsAllocation"];

            List<EarningsAllocationPartner> list = new List<EarningsAllocationPartner>();
            IEnumerable<Multigroup.DomainModel.Shared.Partner> partners = _partnerService.GetPartners();


            foreach (Multigroup.DomainModel.Shared.Partner partner in partners)
            {
                EarningsAllocationPartner part = new EarningsAllocationPartner();
                part.Partner = partner.Name;
                part.PartnerId = partner.PartnerId;
                part.Percentage = partner.Percentage;
                part.Amount = partner.Percentage * amount / 100;
                list.Add(part);
            }

            principal.Partners = list;

            Session["SessionEarningsAllocation"] = principal;

            return PartialView("~/Views/EarningsAllocation/PartnersTable.cshtml", principal);

        }

    }
}

Multigroup.Portal/Views/EarningsAllocation/EarningsAllocation.cshtml
<!-- VISTA: Maintenance/EarningsAllocation.cshtml -->
@model Multigroup.Portal.Models.Administration.EarningsAllocationFilterVm
<div class="clearfix">
</div>
<div class="row">
    <div class="col-md-12 column">
        <div class="portlet light bordered">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-EarningsAllocation"></i>
                    <span class="caption-subject bold uppercase">Aignación de Ganancias</span>
                </div>
                <div class="actions">
                    <a class="btn btn-default" id="btnAddEarningsAllocation">Añadir</a>
                    <div class="tooltipAai btn-group" id="idTooltipAai">
                        <a class="btn btn-default bootstro" id="btnViewEarningsAllocation" disabled="disabled">
                            Ver
                        </a>
                    </div>
                    <div class="tooltipAai btn-group" id="idTooltipAai">
                        <a class="btn btn-default bootstro" id="btnEditEarningsAllocation" disabled="disabled">
                            Editar
                        </a>
                    </div>
                    <a class="btn btn-icon-only btn-default fullscreen" href="javascript:;" data-original-title="" title="">
                    </a>
                </div>
            </div>
            <div class="portlet-body form">
                <div class="row">
                    <div class="col-md-3">
                        <div class="form-group">
                            <label class="control-label col-md-4">Fecha Desde:</label>
                            <div class="col-md-8">
                                <input type="text" class="form-control form-control-inline date-picker" id="txtDateFrom" placeholder="dd/mm/aaaa" />
                            </div>
                        </div>
                    </div>
                    <div class="col-md-3">
                        <div class="form-group">
                            <label class="control-label col-md-4">Fecha Hasta:</label>
                            <div class="col-md-8">
                                <input type="text" class="form-control form-control-inline date-picker" id="txtDateTo" placeholder="dd/mm/aaaa" />
                            </div>
                        </div>
                    </div>
                    <div class="col-md-3">
                        <div class="form-group">
                            <label class="control-label col-md-4">Usuario Creador:</label>
                            <div class="col-md-8">
                                @Html.DropDownListFor(m => m.SelectedUser, Model.ListUser, new { @size = "2" })
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-3">
                        <div class="form-group">
                            <label class="control-label col-md-4">Monto Desde:</label>
                            <div class="col-md-8">
                                @Html.TextBoxFor(model => model.AmountFrom, new { @class = "form-control", @type = "number", @Value = "" })
                            </div>
                        </div>
                    </div>
                    <div class="col-md-3">
                        <div class="form-group">
                            <label class="control-label col-md-4">Monto Hasta:</label>
                            <div class="col-md-8">
                                @Html.TextBoxFor(model => model.AmountTo, new { @class = "form-control", @type = "number", @Value = "" })
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-3">
                        <div class="form-group">
                            <div class="col-md-12">
                                <button id="btnBuscar" class="btn btn-default">Buscar</button>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row" id="table">
                    <div class="col-md-12" id="acciones">

                    </div>
                </div>
            </div>
        </div>
        <div class="portlet portlet-sortable-empty">
        </div>
    </div>
</div>
<div class="modal fade" role="dialog" id="modalViewEarningsAllocation">

</div>
<!-- Note the missing multiple attribute! -->
<script type="text/javascript">
    $(document).ready(function () {

        $('.date-picker').datepicker();
        $('select').multiselect({
            includeSelectAllOption: true,
            enableFiltering: false,
        });
        $('.tooltipAai').tooltip({
            container: 'body',
            title: "Seleccione un gasto"
        });
        $('.tooltipEarningsAllocation1').tooltip({
            container: 'body',
            title: 'Seleccione un gasto'
        });
        $('#btnViewEarningsAllocation').click(function (event) {
            CallBackGet(function (data) {
                $("#dashboard").html(data);
            }, "/EarningsAllocation/View?id=" + id, null)
        });

        $('#btnEditEarningsAllocation').click(function (event) {
            CallBackGet(function (data) {
                $("#dashboard").html(data);
            }, "/EarningsAllocation/Edit?id=" + id, null)
        });

        $('#btnAddEarningsAllocation').click(function (event) {
            CallBackGet(function (data) {
                $("#dashboard").html(data);
            }, "/EarningsAllocation/Create", null)
        });

        $('#btnBuscar').click(function (event) {
            var params = {};
            params.SelectedUser = $('#SelectedUser').val();
            params.AmountFrom = $('#AmountFrom').val();
            params.AmountTo = $('#AmountTo').val();;
            params.DateFrom = $('#txtDateFrom').val();
            params.DateTo = $('#txtDateTo').val();
            params.Receipt = $('#Receipt').val();
            CallBackGet(function (data) {
                $("#acciones").html(data);
            }, "/EarningsAllocation/GetTable", params)
        });

    });
</script>

Multigroup.Portal/Views/EarningsAllocation/EarningsAllocationTable.cshtml
<!-- VISTA: User/UserList.cshtml -->
@model Multigroup.Portal.Models.Administration.EarningsAllocationTableVm

<div class="form-group">
    <table id="tabla_id" class="display table table-bordered table-striped table-condensed flip-content" style="overflow: hidden; white-space: nowrap; text-overflow: ellipsis;">
        <thead>
            <tr>
                <th style="display: none">Número</th>
                <th>Fecha</th>
                <th>Concepto</th>
                <th>Monto</th>
                <th>Fecha Sistema</th>/th>
                <th>Usuario</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.EarningsAllocationList)
            {
                <tr>
                    <td style="display: none">@Html.DisplayFor(modelItem => item.EarningsAllocationId)</td>
                    <td>@Html.DisplayFor(modelItem => item.Date)</td>
                    <td>@Html.DisplayFor(modelItem => item.Concept)</td>
                    <td>@Html.DisplayFor(modelItem => item.Amount)</td>
                    <td>@Html.DisplayFor(modelItem => item.SystemDate)</td>
                    <td>@Html.DisplayFor(modelItem => item.User)</td>
                </tr>
            }
        </tbody>
    </table>
</div>
<script type="text/javascript">
    $(document).ready(function () {
        function formatTableToolsButton(node) {
            $(node).removeClass('DTTT_button');
            $(node).addClass('btn btn-default');
        }
        var table = $('#tabla_id').dataTable({
            "destroy": true,
            "aaSorting": [],
            "bServerSide": false,
            "lengthMenu": [[10, 50, 200, 500, -1], [10, 50, 200, 500, "Todos"]],
            "dom": 'Blfrtip',
            "buttons": [
                { extend: 'copy', text: 'Copiar' },
                'csv',
                'excel',
                'pdf',
                { extend: 'print', text: 'Imprimir' },
            ],
            "sScrollYInner": "100%",
            "sScrollX": "100%",
            "sScrollXInner": "100%",
            "scrollCollapse": true,
            "bProcessing": false
        });

        $('#tabla_id tbody').unbind("click").on('click', 'tr', function (event) {
            event.stopPropagation();
            if ($(this).hasClass('selected')) {
                $(this).removeClass('selected');
                $("#btnVer").attr("disabled", "disabled");
                $("#idTooltipEarningsAllocation1").removeClass('tooltipAai');
                $('#idTooltipEarningsAllocation1').tooltip({
                    container: 'body',
                    title: 'Seleccione un empleado'
                });
                $("#btnViewEarningsAllocation").attr("disabled", "disabled");
                $("#btnEditEarningsAllocation").attr("disabled", "disabled");
                $("#idTooltipAai").removeClass('tooltipAai');
                $('#idTooltipAai').tooltip({
                    container: 'body',
                    title: "Seleccione un empleado"
                });
            }
            else {
                $('#tabla_id tr.selected').removeClass('selected');
                $(this).addClass('selected');
                $("#btnViewEarningsAllocation").removeAttr("disabled", "disabled");
                $("#btnEditEarningsAllocation").removeAttr("disabled", "disabled");
                $("#idTooltipAai").tooltip('destroy');
                $("#btnVer").removeAttr("disabled", "disabled");
                $("#idTooltipEarningsAllocation1").tooltip('destroy');
                id = table.fnGetData(this)[0];
            }
        });
    });
</script>

Multigroup.Portal/Views/EarningsAllocation/EarningsAllocationView.cshtml
@model Multigroup.Portal.Models.Administration.EarningsAllocationVm
<div class="filter-container">
</div>

<div class="clearfix">
</div>
<div class="row">
    <div class="col-md-12 column">
        <div class="portlet light bordered">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-laptop"></i>
                    <span class="caption-subject bold uppercase">Ver Asignación de Ganancias</span>
                </div>
                <div class="actions">
                    <a class="btn btn-icon-only btn-default fullscreen" href="javascript:;" data-original-title="" title="">
                    </a>
                </div>
            </div>
        @using (Ajax.BeginForm("Create", "EarningsAllocation", new AjaxOptions
                                {
                                    HttpMethod = "POST",
                                    OnBegin = "OnStartIngresoTrabajo",
                                    OnComplete = "OnComplete",
                                    OnFailure = "FailMessage",
                                    OnSuccess = "SuccessMessageIngresoTrabajo",
                                    UpdateTargetId = "dashboard"
                                }))
                                {
            @Html.AntiForgeryToken()
        <div class="portlet-body form">
            <div class="row">
                <div class="col-md-4">
                    <div class="form-group">
                        <label class="control-label col-md-3">Fecha:</label>
                        <div class="col-md-9">
                            @Html.TextBoxFor(model => model.Date, new { @class = "form-control form-control-inline date-picker", @type = "text", @placeholder = "dd/mm/aaaa", @readonly = true })
                            @Html.ValidationMessageFor(model => model.Date, string.Empty, new { @class = "validate-error" })
                        </div>
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="form-group">
                        <label class="control-label col-md-4">Monto:</label>
                        <div class="col-md-8">
                            @Html.TextBoxFor(model => model.Amount, new { @class = "form-control", @type = "number", @readonly = true })
                            @Html.ValidationMessageFor(model => model.Amount, string.Empty, new { @class = "validate-error" })
                        </div>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="form-group">
                        <label class="control-label col-md-3">Concepto:</label>
                        <div class="col-md-9">
                            @Html.TextBoxFor(model => model.Concept, new { @class = "form-control", @readonly = true })
                            @Html.ValidationMessageFor(model => model.Concept, string.Empty, new { @class = "validate-error" })
                        </div>
                    </div>
                </div>
            </div>           
            <br />
            <div class="row">
                <div class="col-md-6">
                    <!-- BEGIN Portlet PORTLET-->
                    <div class="portlet box blue-dark">
                        <div class="portlet-title">
                            <div class="caption">
                                <i class="fa fa-calculator"></i>Socios
                            </div>
                        </div>
                        <div class="portlet-body">
                            <div id="paymentsTableDiv" style="position: relative; overflow: hidden; width: auto; min-height: 200px;">
                                <table id="paymentsTable" class="display table table-bordered table-striped table-condensed flip-content" style="overflow: hidden; white-space: nowrap; text-overflow: ellipsis;">
                                    <thead>
                                        <tr>
                                            <th style="display: none">Id</th>
                                            <th>Nombre</th>
                                            <th>% Capital</th>
                                            <th>Ganancia Asignada</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @foreach (var item in Model.Partners)
                                        {
                                            <tr>
                                                <td style="display: none">@item.PartnerId</td>
                                                <td>@item.Partner</td>
                                                <td>@item.Percentage</td>
                                                <td>@item.Amount</td>
                                            </tr>
                                        }
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                    <!-- END Portlet PORTLET-->
                </div>
            </div>
            <br />           
            <div class="form-actions">
                <div class="row">
                    <div class="col-md-offset-5">
                        <a class="btn btn-primary" id="btnVolver">Volver</a>
                    </div>
                </div>
            </div>
        </div>
            }
        </div>
    </div>
</div>

<script type="text/javascript">
    $(document).ready(function () {


        $("#Date").datepicker();
        $('select').multiselect();      

        $('#btnVolver').click(function (event) {
            CallBackGet(function (data) {
                $("#dashboard").html(data);
            }, "/EarningsAllocation/Index", null)
        });

    });
</script>

Multigroup.Portal/Views/EarningsAllocation/PartnersTable.cshtml
@using Resources
@model Multigroup.Portal.Models.Administration.EarningsAllocationVm

<table id="partnersTable" class="display table table-bordered table-striped table-condensed flip-content" style="overflow: hidden; white-space: nowrap; text-overflow: ellipsis;">
    <thead>
        <tr>
            <th style="display: none">Id</th>
            <th>Nombre</th>
            <th>% Capital</th>
            <th>Ganancia Asignada</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Partners)
        {
        <tr>
            <td style="display: none">@item.PartnerId</td>
            <td>@item.Partner</td>
            <td>@item.Percentage</td>
            <td>@item.Amount</td>
        </tr>
        }
    </tbody>
</table>
<script type="text/javascript">
    $(document).ready(function () {

        $('select').multiselect();


        $('#partnersTable tbody').unbind("click").on('click', 'tr', function (event) {
            event.stopPropagation();
            ParterId = tableArticles.fnGetData(this)[0];
          
            if ($(this).hasClass('selected')) {
                $(this).removeClass('selected');
            }
            else {
                $('#partnersTable tr.selected').removeClass('selected');
                $(this).addClass('selected');
            }
        });
        $('#btnAddArticle').click(function (event) {
            var param = new Object;
            param.QuantityArticle = $('#QuantityArticle').val();
            param.ArticleId = $('#Articles').val();
            param.PriceArticle = $('#PriceArticle').val();
            param.DescriptionArticle = $('#DescriptionArticle').val();
            if (param.PriceArticle == '' || param.QuantityArticle == '') {
                Command: toastr["error"]("El Precio y la Cantidad son Obligatorios.")
                toastr.options = {
                    "closeButton": true,
                    "debug": false,
                    "newestOnTop": false,
                    "progressBar": false,
                    "positionClass": "toast-top-center",
                    "preventDuplicates": true,
                    "onclick": null,
                    "showDuration": "300",
                    "hideDuration": "1000",
                    "timeOut": "5000",
                    "extendedTimeOut": "1000",
                    "showEasing": "swing",
                    "hideEasing": "linear",
                    "showMethod": "fadeIn",
                    "hideMethod": "fadeOut"
                }
            }
            else
            CallBackGet(function (data) {
                $('#partnersModal').modal('hide');
                $('.modal-backdrop').remove();
                $("#partnersTableDiv").html(data);
                $("#btnPurchase").attr("disabled", "disabled");
                $("#btnScheduled").attr("disabled", "disabled");
                $("#btnExpense").attr("disabled", "disabled");
                $('#Amount').val(total);
            }, "/EarningsAllocation/Articles", param)
        });
    });
</script>