Multigroup.Portal/Models/Shared/AccountVm.cs
using Multigroup.DomainModel.Shared;
using System.ComponentModel.DataAnnotations;

namespace Multigroup.Portal.Models.Shared
{
    public class AccountVm
    {
        public string Name { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }

        [Required]
        [Display(Name = "Nombre de usuario")]
        public string UserName { get; set; }

        [Required]
        [StringLength(100, ErrorMessage = "El número de caracteres de {0} debe ser al menos {2}.", MinimumLength = 6)]
        [DataType(DataType.Password)]
        [Display(Name = "Contraseña")]
        public string Password { get; set; }

        [DataType(DataType.Password)]
        [Display(Name = "Confirmar contraseña")]
        [Compare("Password", ErrorMessage = "La contraseña y la contraseña de confirmación no coinciden.")]
        public string ConfirmPassword { get; set; }

        public User ToModelObject()
        {
            return new User
            {
                Email = Email,
                Names = Name,
                Surname = LastName,
                UserName = UserName,
                Password = Password,
            };
        }
    }
}

Multigroup.Portal/Models/Shared/BaseVm.cs
using Multigroup.Portal.Providers;
using Multigroup.Portal.Utilities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Multigroup.Portal.Models.Shared
{
    public class BaseVm
    {
        public int? GetNullableValue(SingleSelectVm ddl)
        {
            return (ddl != null) ? Util.ParseIntNullable(ddl.SelectedItem) : null;
        }

        public int? GetValue(SingleSelectVm ddl)
        {
            if (ddl != null)
            {
                return Util.ParseIntNullable(ddl.SelectedItem);
            }
            else
                return 0;
        }

        public IEnumerable<string> GetValue(MultiSelectVm ddl)
        {
            return (ddl != null) ? ddl.SelectedItems : null;
        }
    }
}

Multigroup.Portal/Models/Shared/ChangePasswordVm.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Multigroup.Portal.Models.Shared
{
    public class ChangePasswordVm
    {
        [Required(ErrorMessage = "El campo es requerido")]
        [DataType(DataType.Password)]
        public string OldPassword { get; set; }

        [Required(ErrorMessage = "El campo es requerido")]
        [StringLength(100, ErrorMessage = "El número de caracteres de {0} debe ser al menos {2}.", MinimumLength = 6)]
        [DataType(DataType.Password)]
        public string NewPassword { get; set; }

        [DataType(DataType.Password)]
        [System.Web.Mvc.Compare("NewPassword", ErrorMessage = "La nueva contraseña y la contraseña de confirmación no coinciden.")]
        public string ConfirmPassword { get; set; }
    }
}

Multigroup.Portal/Models/Shared/Charts/BarChartVm.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Multigroup.Portal.Models.Shared.Charts
{
    public class BarChartVm
    {
        public List<IEnumerable<object>> resultset { get; set; }
        public List<Metadata> metadata { get; set; }
    }
}

Multigroup.Portal/Models/Shared/Charts/Data.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Multigroup.Portal.Models.Shared.Charts
{
    public class Data
    {
        public float value { get; set; }
        public string label { get; set; }
        public string description { get; set; }
        public double Id { get; set; }
    }
}

Multigroup.Portal/Models/Shared/Charts/IBarChartVm.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Multigroup.Portal.Models.Shared.Charts
{
    public interface IBarChartVm
    {
        BarChartVm BuildChart(object sources, params object[] parameters);
    }
}

Multigroup.Portal/Models/Shared/Charts/ILineChartVm.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Multigroup.Portal.Models.Shared.Charts
{
    public interface ILineChartVm
    {
        LineChartVm BuildChart(object sources);
    }
}

Multigroup.Portal/Models/Shared/Charts/IPieChart.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Multigroup.Portal.Models.Shared.Charts
{
    public interface IPieChartVm
    {
        PieChartVm BuildChart(object sources);
    }
}

Multigroup.Portal/Models/Shared/Charts/LineChartVm.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Multigroup.Portal.Models.Shared.Charts
{
    public class LineChartVm
    {
        public List<IEnumerable<object>> resultset { get; set; }
        public List<Metadata> metadata { get; set; }

        public double orthoAxisFixedMin { get; set; }
    }
}

Multigroup.Portal/Models/Shared/Charts/Metadata.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Multigroup.Portal.Models.Shared.Charts
{
    public class Metadata
    {
        public int colIndex { get; set; }
        public string colType { get; set; }
        public string colName { get; set; }
    }
}

Multigroup.Portal/Models/Shared/Charts/PieChartVm.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Multigroup.Portal.Models.Shared.Charts
{
    public class PieChartVm
    {
        public List<IEnumerable<object>> resultset { get; set; }
        public List<Metadata> metadata { get; set; }
    }
}

Multigroup.Portal/Models/Shared/Charts/RadarChart.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Multigroup.Portal.Models.Shared.Charts
{
    public class RadarChart
    {
        public List<object> labels { get; set; }
        public List<object> datasets { get; set; }
    }
}

Multigroup.Portal/Models/Shared/CustomerDebtTableVm .cs
using Multigroup.DomainModel.Shared;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Multigroup.Portal.Models.Shared
{
    public class CustomerDebtTableVm
    {
        public IEnumerable<CustomerDebtListVm> CustomerDebtList { get; set; }

        public static CustomerDebtTableVm ToViewModel(IEnumerable<CustomerDebt> entities)
        {
            return new CustomerDebtTableVm
            {
                CustomerDebtList = CustomerDebtListVm.ToViewModelList(entities),
            };
        }
    }

    public class CustomerDebtListVm
    {
        public int Number { get; set; }
        public string IdentificationNumber { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string StatusContract { get; set; }
        public string Color { get; set; }
        public string Count { get; set; }
        public string Amount { get; set; }
        public string Interest { get; set; }
        public string Total { get; set; }
        public string User { get; set; }

        public static IEnumerable<CustomerDebtListVm> ToViewModelList(IEnumerable<CustomerDebt> entities)
        {
            return entities.Select(x => new CustomerDebtListVm
            {
                Number = x.Number,
                IdentificationNumber = x.IdentificationNumber,
                Name = x.Name,
                Surname = x.Surname,
                Color = x.Color,
                Count = x.Count,
                Amount = x.Amount,
                StatusContract = x.StatusContract,
                Interest = x.Interest,
                Total = x.Total,
                User = x.User,
            });
        }
    }
}

Multigroup.Portal/Models/Shared/DataTable/JQueryDataTablesModel.cs
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Web;

namespace Multigroup.Portal.Models.Shared.DataTable
{
    /// <summary>
    /// Represents the jQuery DataTables request that is sent for server
    /// side processing.
    /// <para>http://datatables.net/usage/server-side</para>
    /// </summary>
    public class JQueryDataTablesModel
    {
        /// <summary>
        /// Gets or sets the information for DataTables to use for rendering.
        /// </summary>
        public int sEcho { get; set; }

        /// <summary>
        /// Gets or sets the display start point.
        /// </summary>
        public int iDisplayStart { get; set; }

        /// <summary>
        /// Gets or sets the number of records to display.
        /// </summary>
        public int iDisplayLength { get; set; }

        /// <summary>
        /// Gets or sets the Global search field.
        /// </summary>
        public string sSearch { get; set; }

        /// <summary>
        /// Gets or sets if the Global search is regex or not.
        /// </summary>
        public bool bRegex { get; set; }

        /// <summary>
        /// Gets or sets the number of columns being display (useful for getting individual column search info).
        /// </summary>
        public int iColumns { get; set; }

        /// <summary>
        /// Gets or sets indicator for if a column is flagged as sortable or not on the client-side.
        /// </summary>
        public ReadOnlyCollection<bool> bSortable_ { get; set; }

        /// <summary>
        /// Gets or sets indicator for if a column is flagged as searchable or not on the client-side.
        /// </summary>
        public ReadOnlyCollection<bool> bSearchable_ { get; set; }

        /// <summary>
        /// Gets or sets individual column filter.
        /// </summary>
        public ReadOnlyCollection<string> sSearch_ { get; set; }

        /// <summary>
        /// Gets or sets if individual column filter is regex or not.
        /// </summary>
        public ReadOnlyCollection<bool> bRegex_ { get; set; }

        /// <summary>
        /// Gets or sets the number of columns to sort on.
        /// </summary>
        public int? iSortingCols { get; set; }

        /// <summary>
        /// Gets or sets column being sorted on (you will need to decode this number for your database).
        /// </summary>
        public ReadOnlyCollection<int> iSortCol_ { get; set; }

        /// <summary>
        /// Gets or sets the direction to be sorted - "desc" or "asc".
        /// </summary>
        public ReadOnlyCollection<string> sSortDir_ { get; set; }

        /// <summary>
        /// Gets or sets the value specified by mDataProp for each column. 
        /// This can be useful for ensuring that the processing of data is independent 
        /// from the order of the columns.
        /// </summary>
        public ReadOnlyCollection<string> mDataProp_ { get; set; }

        public ReadOnlyCollection<SortedColumn> GetSortedColumns()
        {
            if (!iSortingCols.HasValue)
            {
                // Return an empty collection since it's easier to work with when verifying against
                return new ReadOnlyCollection<SortedColumn>(new List<SortedColumn>());
            }

            var sortedColumns = new List<SortedColumn>();
            for (int i = 0; i < iSortingCols.Value; i++)
            {
                sortedColumns.Add(new SortedColumn(mDataProp_[iSortCol_[i]], sSortDir_[i]));
            }

            return sortedColumns.AsReadOnly();
        }
    }

    /// <summary>
    /// Represents a sorted column from DataTables.
    /// </summary>
    public class SortedColumn
    {
        private const string Ascending = "asc";

        public SortedColumn(string propertyName, string sortingDirection)
        {
            PropertyName = propertyName;
            Direction = sortingDirection.Equals(Ascending) ? SortingDirection.Ascending : SortingDirection.Descending;
        }

        /// <summary>
        /// Gets the name of the Property on the class to sort on.
        /// </summary>
        public string PropertyName { get; private set; }

        public SortingDirection Direction { get; private set; }

        public override int GetHashCode()
        {
            var directionHashCode = Direction.GetHashCode();
            return PropertyName != null ? PropertyName.GetHashCode() + directionHashCode : directionHashCode;
        }

        public override bool Equals(object obj)
        {
            if (obj == null)
            {
                return false;
            }

            if (GetType() != obj.GetType())
            {
                return false;
            }

            var other = (SortedColumn)obj;

            if (other.Direction != Direction)
            {
                return false;
            }

            return other.PropertyName == PropertyName;
        }
    }

    /// <summary>
    /// Represents the direction of sorting for a column.
    /// </summary>
    public enum SortingDirection
    {
        Ascending,
        Descending
    }
}

Multigroup.Portal/Models/Shared/DataUploadFilesResultVm.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Multigroup.Portal.Models.Shared
{
    public class DataUploadFilesResultVm
    {
        public string Name { get; set; }
        public int Length { get; set; }
        public string Path { get; set; }
    }
}

Multigroup.Portal/Models/Shared/ImageVm.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Multigroup.Portal.Models.Shared
{
    public class ImageVm
    {
        public string Url { get; set; }
    }
}

Multigroup.Portal/Models/Shared/LoginAccountVm.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Multigroup.Portal.Models.Shared
{
    public class LoginAccountVm
    {
        public LoginVm UserLogin { get; set; }

        public AccountVm Account { get; set; }
    }
}

Multigroup.Portal/Models/Shared/LoginVm.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Multigroup.Portal.Models.Shared
{
    public class LoginVm
    {
        [Required]
        [Display(Name = "Nombre de usuario")]
        public string UserName { get; set; }

        [Required]
        [DataType(DataType.Password)]
        [Display(Name = "Contraseña")]
        public string Password { get; set; }

        [Display(Name = "¿Recordar cuenta?")]
        public bool RememberMe { get; set; }
    }
}

Multigroup.Portal/Models/Shared/LostPasswordVm.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Multigroup.Portal.Models.Shared
{
    public class LostPasswordVm
    {
        [Required(ErrorMessage = "Necesitamos su nombre de usuario para recuperar la contraseña")]
        public string UserName { get; set; }
    }
}

Multigroup.Portal/Models/Shared/MappingTableVm.cs
using Multigroup.DomainModel.Shared;
using System;
using System.Collections.Generic;
using System.Linq;

namespace Multigroup.Portal.Models.Shared
{
    public class MappingTableVm
    {
        public IEnumerable<MappingItemVm> MappingTests { get; set; }
        public IEnumerable<MappingItemVm> MappingComponents { get; set; }
    }

    public class MappingItemVm
    {
        public int Id { get; set; }
        public string SourceName { get; set; }
        public string CodeArgos { get; set; }
        public string CodeExternal { get; set; }

        public static IEnumerable<MappingItemVm> ToViewModelList(IEnumerable<Mapping> entities)
        {
            return entities.Select(x => new MappingItemVm { 
                Id = x.Id,
                CodeArgos = x.CodeArgos,
                CodeExternal = x.CodeExternal,
                SourceName = x.MapperType.Description
            });
        }
    }
}

Multigroup.Portal/Controllers/MenuController.cs
using Multigroup.DomainModel.Shared;
using Multigroup.DomainModel.Shared.Constants;
using Multigroup.Portal.Models.Menu;
using Multigroup.Portal.Providers;
using Multigroup.Services.Menu;
using Multigroup.Services.Shared;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Multigroup.Portal.Controllers
{
    public class MenuController : Controller
    {
        private UserLoginProvider _userLoginProvider;
        private ProfileProvider _profileProvider;
        private MenuService _menuService;

        public MenuController()
        {
            _userLoginProvider = new UserLoginProvider();
            _profileProvider = new ProfileProvider();
            _menuService = new MenuService();
        }

        // GET: Menu
        public ActionResult Index()
        {
            var items = _menuService.GetCurrentMenu(_profileProvider.CurrentUserId, MenuTypeCon.Left);
            IEnumerable<MenuComponentVm> menu = MenuComponentVm.ToViewModel(items);
            return PartialView("MenuAdmin", menu);
        }
    }
}

Multigroup.Portal/Views/Shared/_Layout.cshtml
@model Multigroup.Portal.Models.HomeVm
<!DOCTYPE html>
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>MG</title>
	<link href="http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700&subset=all" rel="stylesheet" type="text/css" />
	@Scripts.Render("~/bundles/jquery")
	@Scripts.Render("~/bundles/bootstrap")
	@Styles.Render("~/Content/css")
	@Scripts.Render("~/bundles/modernizr")

	

	<script src="~/Scripts/ckeditor/ckeditor.js"></script>
	<script type="text/javascript" src="~/Scripts/pivot.es.min.js"></script>
	<script type="text/javascript" src="~/Scripts/gchart_renderers.js"></script>
	<link rel="apple-touch-icon" sizes="57x57" href="~/Assets/icons/apple-icon-57x57.png">
	<link rel="apple-touch-icon" sizes="60x60" href="~/Assets/icons/apple-icon-60x60.png">
	<link rel="apple-touch-icon" sizes="72x72" href="~/Assets/icons/apple-icon-72x72.png">
	<link rel="apple-touch-icon" sizes="76x76" href="~/Assets/icons/apple-icon-76x76.png">
	<link rel="apple-touch-icon" sizes="114x114" href="~/Assets/icons/apple-icon-114x114.png">
	<link rel="apple-touch-icon" sizes="120x120" href="~/Assets/icons/apple-icon-120x120.png">
	<link rel="apple-touch-icon" sizes="144x144" href="~/Assets/icons/apple-icon-144x144.png">
	<link rel="apple-touch-icon" sizes="152x152" href="~/Assets/icons/apple-icon-152x152.png">
	<link rel="apple-touch-icon" sizes="180x180" href="~/Assets/icons/apple-icon-180x180.png">
	<link rel="icon" type="image/png" sizes="192x192" href="~/Assets/icons/android-icon-192x192.png">
	<link rel="icon" type="image/png" sizes="32x32" href="~/Assets/icons/favicon-32x32.png">
	<link rel="icon" type="image/png" sizes="96x96" href="~/Assets/icons/favicon-96x96.png">
	<link rel="icon" type="image/png" sizes="16x16" href="~/Assets/icons/favicon-16x16.png">
	<link rel="manifest" href="/manifest.json">
	<meta name="msapplication-TileColor" content="#ffffff">
	<meta name="msapplication-TileImage" content="~/Assets/icons/ms-icon-144x144.png">
	<meta name="theme-color" content="#ffffff">
	<script src="~/Scripts/d3.min.js"></script>
</head>
<body class="page-header-fixed page-quick-sidebar-over-content page-sidebar-closed-hide-logo page-container-bg-solid" id="">
	<div id="spinner" class="spinner" style="display:none;">
		<img id="img-spinner" src="~/Assets/img/spinner.gif" alt="Cargando" />
	</div>
	<div id="errorAjax" class="alert alert-danger spinner" style="display:none;">
		<strong>Error!</strong> al cargar contenido
	</div>
	<!-- COMIENZO HEADER -->
	<div class="page-header navbar navbar-fixed-top">
		<!-- COMIENZO HEADER INNER -->
		<div class="page-header-inner">
			<!-- COMIENZO LOGO -->
			<div class="page-logo">
				<a href="#">
					<img src="~/Assets/img/logo.png" alt="logo" class="logo-default" />
				</a>
				<div class="menu-toggler sidebar-toggler hide">
				</div>
			</div>
			<!-- FIN LOGO -->
			<!-- COMIENZO MENU TOGGLER -->
			<a href="javascript:;" class="menu-toggler responsive-toggler" data-toggle="collapse" data-target=".navbar-collapse">
			</a>
			<!-- FIN MENU TOGGLER -->
			<!-- COMIENZO BUSCAR -->
			<!-- <div class="search" id="main-search">
				<input type="text" class="form-control underline-input" placeholder="Buscar...">
			</div> -->
			<!-- FIN BUSCAR -->
			<!-- COMIENZO BARRA SUPERIOR -->
			<div class="top-menu">
				<ul class="nav navbar-nav pull-right">
					<!-- COMIENZO PERFIL USUARIO -->
					<li class="dropdown dropdown-user">
						<a href="javascript:;" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-close-others="true">
							<img alt="" class="img-circle" src="../assets/img/perfil.png" />
							<span class="username username-hide-on-mobile">
								@Model.UserProfile.UserName
							</span>
							<i class="fa fa-angle-down"></i>
						</a>
						<ul class="dropdown-menu dropdown-menu-default">
							<li>
								@using (Html.BeginForm("LogOff", "Account"))
								{
									<a id="btnLogOff" onclick="$(this).parents('form').submit();"><i class="fa fa-sign-out"></i>Salir</a>
								}

							</li>
						</ul>
					</li>
					<!-- FIN PERFIL USUARIO -->
				</ul>
			</div>
			<!-- FIN TOP BARRA SUPERIOR -->
		</div>
	</div>
	<!-- FIN HEADER -->
	<div class="clearfix">
	</div>
	<!-- COMIENZO CONTAINER -->
	<div class="page-container">
		<!-- COMIENZO SIDEBAR -->
		@Html.Action("Index", "Menu")
		<!-- FIN SIDEBAR -->
		<!-- COMIENZO CONTENT -->
		<div class="page-content-wrapper">
			<div class="page-content" id="homeIndex">
				@RenderBody()
				<!-- END CONTENT -->
			</div>
			<div class="scrollToTop"></div>
		</div>
		<!-- END CONTAINER -->
		<!-- BEGIN FOOTER -->
		<div class="page-footer">
			<div class="page-footer-inner">
				2018 &copy; IngarX
			</div>
			<div class="scroll-to-top">
				<i class="icon-arrow-up"></i>
			</div>
		</div>
		<!-- END FOOTER -->
		@RenderSection("scripts", required: false)
	</div>

	<script type="text/javascript">
		$(document).ready(function () {
			//BOTON IR AL CIELO
			$(window).scroll(function () {
				if ($(this).scrollTop() > 100) {
					$('.scrollToTop').fadeIn();
				} else {
					$('.scrollToTop').fadeOut();
				}
			});
			$('.scrollToTop').click(function () {
				$('html, body').animate({ scrollTop: 0 }, 800);
				return false;
			});
		});
	</script>

	<!-- INICIO VARIOS -->
	<script type="text/javascript">
		jQuery(document).ready(function () {
			Metronic.init();
			Layout.init();
			PortletDraggable.init();
			$('#mostrartodos').iCheck({
				checkboxClass: 'icheckbox_square-grey',
				radioClass: 'iradio_square-grey',
				increaseArea: '20%' // optional
			});
			$('#cambio').iCheck({
				checkboxClass: 'icheckbox_square-grey',
				radioClass: 'iradio_square-grey',
				increaseArea: '20%' // optional
			});
		});
		function SuccessMessageHome(result) {
			$('#SucursalModal').modal('hide');
			$('.modal-backdrop').remove();
		}

		//ESCONDER MENU SIDEBAR
		$("#toggleSidebar").click(function () {
			if ($('#sidebarMenu').hasClass('page-sidebar-menu-closed') == false) {
				$(this).css('transform', 'rotateY(180deg)');
				$('.widget-body.welcome-box.tabular').hide();
			} else {
				$(this).css('transform', 'rotateY(360deg)');
				$('.widget-body.welcome-box.tabular').show();
			}
		});
		//CLICK ENTRADAS DE MENU
		$(".sub-menu li").on("click", function () {
			if (!$(this).hasClass('first-submenu')) {
				$(".page-sidebar-menu li").removeClass("active open");
				$(this).addClass("active");
				$(this).parents().eq(1).addClass("active open");
			}
		});
		function SuccessMessage() {
			Command: toastr["success"]("Los datos se guardaron correctamente")

			toastr.options = {
				"closeButton": true,
				"debug": false,
				"newestOnTop": false,
				"progressBar": false,
				"positionClass": "toast-top-center",
				"preventDuplicates": false,
				"onclick": null,
				"showDuration": "10",
				"hideDuration": "10",
				"timeOut": "5000",
				"extendedTimeOut": "1000",
				"showEasing": "swing",
				"hideEasing": "linear",
				"showMethod": "fadeIn",
				"hideMethod": "fadeOut"
			}
		}
	</script>
</body>
</html>