Multigroup.Portal/Controllers/Administration/SallaryPaymentController.cs
using Multigroup.Common.Logging;
using Multigroup.Portal.Filters;
using Multigroup.Portal.Models.Administration;
using Multigroup.Services.Shared;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Multigroup.Portal.Helpers;
using Multigroup.DomainModel.Shared;
using Multigroup.Portal.Models.Maintenance;
using Multigroup.Portal.Utilities;
using Multigroup.Portal.Providers;
using System.Web.UI.WebControls;

namespace Multigroup.Portal.Controllers.Administration
{
    public class SallaryPaymentController : Controller
    {
        private SpendingPaymentService _SpendingPaymentService;
        private IAuditLogHelper _auditLogHelper;
        private UserTypeService _userTypeService;
        private UserService _userService;
        private ProviderService _providerService;
        private ProfileProvider _profileProvider;
        private PurchaseRequestService _purchaseRequestService;
        private ScheduledExpenseService _scheduledExpenseService;
        private ExpenseAuthorizationService _expenseAuthorizationService;
        private PaymentMethodsService _paymentMethodsServvice;
        private SpendingService _spendingService;
        private CashierService _cashierService;

        public SallaryPaymentController()
        {
            _SpendingPaymentService = new SpendingPaymentService();
            _auditLogHelper = new AuditLogHelper();
            _userTypeService = new UserTypeService();
            _userService = new UserService();
            _providerService = new ProviderService();
            _profileProvider = new ProfileProvider();
            _purchaseRequestService = new PurchaseRequestService();
            _scheduledExpenseService = new ScheduledExpenseService();
            _expenseAuthorizationService = new ExpenseAuthorizationService();
            _paymentMethodsServvice = new PaymentMethodsService();
            _spendingService = new SpendingService();
            _cashierService = new CashierService();
        }

        // GET: /SpendingPayment/
        [LogActionFilter]
        [Description("SpendingPayments")]
        public ActionResult Index()
        {
            SpendingPaymentFilterVm model = new SpendingPaymentFilterVm();
            var collections = new CollectionHelper();
            model.ListProvider = new SelectList(_providerService.GetEmployeesWithId(), "ProviderId", "Name");
            model.ListUser = new SelectList(_userService.GetUsersComplete(), "UserId", "Names");
            model.UserId = _profileProvider.CurrentUserId;
            Session["ImputProvider"] = null;
            Session["SpendingImputModel"] = null;
            Session["ImputSpending"] = new List<int>();
            return PartialView("~/Views/SallaryPayment/SallaryPayment.cshtml", model);
        }
        public ActionResult GetTable(int? SelectedProvider, int? SelectedUser, string DateFromExecution, string DateToExecution, string DateFromSystem, string DateToSystem, string AmountFrom, string AmountTo, string BalanceFrom, string BalanceTo, string Receipt, string PositiveBalance)
        {
            var model = SpendingPaymentTableVm.ToViewModel(_SpendingPaymentService.GetSallaryPaymentSummary(SelectedProvider, SelectedUser, DateFromExecution, DateToExecution, DateFromSystem, DateToSystem, AmountFrom, AmountTo, BalanceFrom, BalanceTo, Receipt, PositiveBalance));
            return PartialView("~/Views/SallaryPayment/SallaryPaymentTable.cshtml", model);
        }

        public ActionResult GetTableDetail(int? SelectedProvider, int? SelectedUser, string DateFromExecution, string DateToExecution, string DateFromSystem, string DateToSystem, string AmountFrom, string AmountTo, string BalanceFrom, string BalanceTo, string Receipt, string PositiveBalance)
        {
            var model = SpendingPaymentDetailTableVm.ToViewModel(_SpendingPaymentService.GetSallaryPaymentDetailSummary(SelectedProvider, SelectedUser, DateFromExecution, DateToExecution, DateFromSystem, DateToSystem, AmountFrom, AmountTo, BalanceFrom, BalanceTo, Receipt, PositiveBalance));
            return PartialView("~/Views/SallaryPayment/SallaryPaymentTableDetail.cshtml", model);
        }


        [LogActionFilter]
        [Description("Crear SpendingPayments")]
        public ActionResult Create()
        {
            ViewBag.provider = "-10";
            var model = new SpendingPaymentVm();
            var collections = new CollectionHelper();
            List<SpendingPaymentDetail> lists = new List<SpendingPaymentDetail>();
            model.Details = lists;
            List<SpendingPaymentPaymentMethod> payment = new List<SpendingPaymentPaymentMethod>();
            model.PaymentMethods = payment;
            model.ExecutionDate = DateTime.Now.ToShortDateString();
            model.ddlProvider = collections.GetEmployeesIdsSingleSelectVm();
            model.ddlUser = collections.GetUsersSingleSelectVm();
            model.ddlUser.SelectedItem = _profileProvider.CurrentUserId.ToString();
            model.ddlPaymentMethods = collections.GetPaymentMethodSingleSelectVm();
            model.ddlPaymentMethodPM = collections.GetPaymentMethodSingleSelectVm();
            model.ddlSpendings = collections.GetSpendingsByEmployeeSingleSelectVm(0);
            model.Saving = _cashierService.GetCashiersById(_userService.GetUserCashierByUserId(_profileProvider.CurrentUserId).CashierId).Name;
            model.ListUser = new SelectList(_userService.GetUsersComplete(), "UserId", "Names");
            Session["SessionSpendingPayment"] = model;
            Session["PMs"] = new List<int>();
            return PartialView("~/Views/SallaryPayment/SallaryPaymentCreate.cshtml", model);
        }

        public JsonResult GetAmoutSpending(int SpendingId)
        {
            var response = _spendingService.GetSpendingsById(SpendingId);

            return Json(response, JsonRequestBehavior.AllowGet);
        }

        public ActionResult IndexSpendings(int ProviderId)
        {
            SpendingPaymentVm model = (SpendingPaymentVm)Session["SessionSpendingPayment"];
            var collections = new CollectionHelper();
            model.ddlSpendings = collections.GetSpendingsByEmployeeSingleSelectVm(ProviderId);
            List<SpendingPaymentDetail> lists = new List<SpendingPaymentDetail>();
            model.Details = lists;
            Session["SessionSpendingPayment"] = model;
            return PartialView("~/Views/SallaryPayment/SpendingsTable.cshtml", model);
        }

        public ActionResult IndexPaymentMethod()
        {
            SpendingPaymentVm model = (SpendingPaymentVm)Session["SessionSpendingPayment"];
            ViewBag.ErrorMessagePayment = "false";
            return PartialView("~/Views/SallaryPayment/PaymentMethodTable.cshtml", model);
        }


        public ActionResult Spendings(int? SpendigId, double AmountSpending)
        {
            bool existe = false;
            SpendingPaymentVm principal = (SpendingPaymentVm)Session["SessionSpendingPayment"];
            if (SpendigId.HasValue)
            {
                SpendingPaymentDetail detail = new SpendingPaymentDetail();
                detail.SpendingId = SpendigId.Value;
                detail.Total = AmountSpending;
                detail.Spending = _spendingService.GetSpendingsById(SpendigId.Value).Period;
                List<SpendingPaymentDetail> list = (List<SpendingPaymentDetail>)principal.Details;
                Int32 id = SpendigId.Value;
                var item = list.FirstOrDefault(x => x.SpendingId == id);
                if (item != null)
                    existe = true;
                else
                    list.Add(detail);
                principal.Details = list;


                double total = 0;

                foreach (SpendingPaymentDetail det in list)
                {
                    total = total + det.Total;
                }
                ViewBag.Total = total.ToString();

                Session["Total"] = total.ToString();
                principal.AmountPayment = total;
                Session["SessionSpendingPayment"] = principal;
                Session["esNuevo"] = false;

                if (existe == false)
                {
                    ViewBag.ErrorMessageTrabajo = "false";
                    return PartialView("~/Views/SallaryPayment/SpendingsTable.cshtml", principal);
                }
                else
                {
                    ViewBag.ErrorMessageTrabajo = "true";
                    return PartialView("~/Views/SallaryPayment/SpendingsTable.cshtml", principal);
                }
            }
            else
            {
                return new HttpStatusCodeResult(HttpStatusCode.InternalServerError, "Seleccione un articulo");
            }
        }

        public ActionResult SpendingsCA()
        {
            SpendingPaymentVm principal = (SpendingPaymentVm)Session["SessionSpendingPayment"];
            ViewBag.ErrorMessageTrabajo = "true";
            return PartialView("~/Views/SallaryPayment/SpendingsTable.cshtml", principal);

        }

        public ActionResult PaymentMethod(int? PaymentMethod, double Amount)
        {
            bool existe = false;
            SpendingPaymentVm principal = (SpendingPaymentVm)Session["SessionSpendingPayment"];
            if (PaymentMethod.HasValue)
            {
                SpendingPaymentPaymentMethod payment = new SpendingPaymentPaymentMethod();
                payment.PaymentMethodId = PaymentMethod.Value;
                payment.PaymentMethod = _paymentMethodsServvice.GetPaymentMethodssById(PaymentMethod.Value).Name;
                payment.Amount = Amount;

                List<int> listPM = (List<int>)Session["PMs"];
                listPM.Add(PaymentMethod.Value);
                Session["PMs"] = listPM;

Multigroup.Portal/Controllers/Maintenance/PaymentMethodsController.cs
using Multigroup.Common.Logging;
using Multigroup.Portal.Filters;
using Multigroup.Portal.Models.Maintenance;
using Multigroup.Services.Shared;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Multigroup.Portal.Helpers;
using Multigroup.DomainModel.Shared;

namespace Multigroup.Portal.Controllers.PaymentMethods
{
    public class PaymentMethodsController : Controller
    {
        private PaymentMethodsService _paymentMethodsService;
        private IAuditLogHelper _auditLogHelper;
        private MPSellerAccountService _mpSellerAccountService;

        public PaymentMethodsController()
        {
            _paymentMethodsService = new PaymentMethodsService();
            _auditLogHelper = new AuditLogHelper();
            _mpSellerAccountService = new MPSellerAccountService();
        }

        // GET: /PaymentMethods/
        [LogActionFilter]
        [Description("PaymentMethodss")]
        public ActionResult Index()
        {
            var model = PaymentMethodsTableVm.ToViewModel(_paymentMethodsService.GetPaymentMethodsSummary());
            return PartialView("~/Views/Maintenance/PaymentMethods/PaymentMethods.cshtml", model);
        }
        public ActionResult GetTable()
        {
            var model = MercadoPagoTableVm.ToViewModel(_mpSellerAccountService.GetMPSellerAccounts());
            return PartialView("~/Views/Maintenance/PaymentMethods/MPTable.cshtml", model);
        }

        public ActionResult GenerateMPAccount(string MPAccountId, int? UserId, string Pass, double? MinAmount, double? MaxAmount, string Token)
        {
            try
            {
                if (MaxAmount == null || MinAmount == null || MPAccountId == null || UserId == null)
                    return new HttpStatusCodeResult(HttpStatusCode.InternalServerError, "Debe completar todos los campos");
                else
                {
                    MPSellerAccount account = new MPSellerAccount();
                    account.MaxAmount = MaxAmount.Value;
                    account.MinAmount = MinAmount.Value;
                    account.MPAccountId = MPAccountId;
                    account.Pass = Pass;
                    account.Token = Token;
                    account.UserId = UserId.Value;
                    _mpSellerAccountService.AddMPSellerAccount(account);

                    return RedirectToAction("GetTable");
                }
            }
            catch (Exception ex)
            {
                return new HttpStatusCodeResult(HttpStatusCode.InternalServerError, "Error al generar Cuenta.");
            }
        }

        [LogActionFilter]
        [Description("Crear PaymentMethodss")]
        public ActionResult Create()
        {
            var model = new PaymentMethodsVm();
            var collections = new CollectionHelper();
            model.ddlPaymentPreference = collections.GetPaymentPreferenceSingleSelectVm();
            return PartialView("~/Views/Maintenance/PaymentMethods/PaymentMethodsCreate.cshtml", model);
        }

        [HttpPost]
        public ActionResult Create(PaymentMethodsVm model)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.InternalServerError, "Faltan campos requeridos");
                }

                _paymentMethodsService.AddPaymentMethods(model.ToModelObject());
                return Index();
            }
            catch (Exception ex)
            {
                var log = new AuditLog()
                {
                    LogLevel = AuditLogLevel.Error,
                    Description = ex.Message,
                    InputParam = model,
                };
                _auditLogHelper.LogAuditFail(log);

                return new HttpStatusCodeResult(HttpStatusCode.InternalServerError, "Error al guardar");
            }
        }
        [LogActionFilter]
        [Description("Editar PaymentMethodss")]
        public ActionResult Edit(int id)
        {
            var entity = _paymentMethodsService.GetPaymentMethods(id);
            var model = PaymentMethodsVm.FromDomainModel(entity);
            var collections = new CollectionHelper();
            model.ddlPaymentPreference = collections.GetPaymentPreferenceSingleSelectVm();
            model.ddlPaymentPreference.SelectedItem = entity.PaymentPreferenceId.ToString();
            return PartialView("~/Views/Maintenance/PaymentMethods/PaymentMethodsEdit.cshtml", model);
        }
        public JsonResult EditMP(int id)
        {
            try
            {
                var entity = _mpSellerAccountService.GetMPSellerAccount(id);
                var model = MercadoPagoVm.FromDomainModel(entity);
                return Json(model, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                Response.StatusCode = 500;
                Response.StatusDescription = "Error al recuperar cuenta de mercado pago.";
                return Json(ex.Message, JsonRequestBehavior.AllowGet);
            }
        }

        public void DeleteMP(int id)
        {
            _mpSellerAccountService.DeleteMPSellerAccounts(id);
        }

        public ActionResult EditMercadoPago(int MPSellerAccountId, string MPAccountId, int? UserId, string Pass, double? MinAmount, double? MaxAmount, string Token)
        {
            try
            {
                if (MPSellerAccountId == null || MaxAmount == null || MinAmount == null || MPAccountId == null || UserId == null)
                    return new HttpStatusCodeResult(HttpStatusCode.InternalServerError, "Debe completar todos los campos");
                else
                {
                    MPSellerAccount account = new MPSellerAccount();
                    account.MPSellerAccountId = MPSellerAccountId;
                    account.MaxAmount = MaxAmount.Value;
                    account.MinAmount = MinAmount.Value;
                    account.MPAccountId = MPAccountId;
                    account.Pass = Pass;
                    account.Token = Token;
                    account.UserId = UserId.Value;
                    _mpSellerAccountService.UpdateMPSellerAccounts(account);

                    return RedirectToAction("GetTable");
                }
            }
            catch (Exception ex)
            {
                return new HttpStatusCodeResult(HttpStatusCode.InternalServerError, "Error al generar Cuenta.");
            }
        }
        [HttpPost]
        public ActionResult Edit(PaymentMethodsVm model)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.InternalServerError, "Faltan campos requeridos");
                }

                _paymentMethodsService.UpdatePaymentMethodss(model.ToModelObject());

                return Index();
            }
            catch (Exception ex)
            {
                var log = new AuditLog()
                {
                    LogLevel = AuditLogLevel.Error,
                    Description = ex.Message,
                    InputParam = model,
                };
                _auditLogHelper.LogAuditFail(log);

                return new HttpStatusCodeResult(HttpStatusCode.InternalServerError, "Error al guardar");
            }
        }
    }
}

Multigroup.Portal/Views/SallaryPayment/PaymentMethodTable.cshtml
@using Resources
@model Multigroup.Portal.Models.Administration.SpendingPaymentVm

<table id="paymentMethodTable" class="display table table-bordered table-striped table-condensed flip-content" style="overflow: hidden; white-space: nowrap; text-overflow: ellipsis;">
    <thead>
        <tr>
            <th style="display: none">Id</th>
            <th>Medio de Pago</th>
            <th>Monto</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.PaymentMethods)
        {
        <tr>
            <td style="display: none">@item.PaymentMethodId</td>
            <td>@item.PaymentMethod</td>
            <td>@item.Amount</td>          
        </tr>
        }
    </tbody>
</table>
<script type="text/javascript">
    $(document).ready(function () {    

        var errorPayment = @ViewBag.ErrorMessagePayment;
       

        if (errorPayment == true) {
            Command: toastr["error"]("El metodo ingresado ya existe.")
            toastr.options = {
                "closeButton": true,
                "debug": false,
                "newestOnTop": false,
                "progressBar": false,
                "positionClass": "toast-top-center",
                "preventDuplicates": true,
                "onclick": null,
                "showDuration": "300",
                "hideDuration": "1000",
                "timeOut": "5000",
                "extendedTimeOut": "1000",
                "showEasing": "swing",
                "hideEasing": "linear",
                "showMethod": "fadeIn",
                "hideMethod": "fadeOut"
            }
        }

        var tablePayments = $('#paymentMethodTable').dataTable({
            "destroy": true, 
            "aaSortitablePaymentsng": [],
            "bServerSide": false,
            "sScrollYInner": "100%",
            "sScrollX": "100%",
            "sScrollXInner": "100%",
            "scrollCollapse": true,
            "bProcessing": false,
            "searching": false,
            "bLengthChange": false
        });

        $('#paymentMethodTable tbody').unbind("click").on('click', 'tr', function (event) {
            event.stopPropagation();
            paymentId = tablePayments.fnGetData(this)[0];
          
            if ($(this).hasClass('selected')) {
                $(this).removeClass('selected');
                $("#btnRemovePaymentMethod").attr("disabled", "disabled");             
            }
            else {
                $('#articlesTable tr.selected').removeClass('selected');
                $(this).addClass('selected');
                $("#btnRemovePaymentMethod").removeAttr("disabled", "disabled");               
            }
        });
    });
</script>

Multigroup.Portal/Views/SallaryPayment/SallaryPaymentView.cshtml
@model Multigroup.Portal.Models.Administration.SpendingPaymentVm
<div class="filter-container">
</div>

<div class="clearfix">
</div>
<div class="row">
    <div class="col-md-12 column">
        <div class="portlet light bordered">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-laptop"></i>
                    <span class="caption-subject bold uppercase">Ver Pago de Sueldo</span>
                </div>
                <div class="actions">
                    <a class="btn btn-icon-only btn-default fullscreen" href="javascript:;" data-original-title="" title="">
                    </a>
                </div>
            </div>
        @using (Ajax.BeginForm("Create", "SallaryPayment", new AjaxOptions
                                {
                                    HttpMethod = "POST",
                                    OnBegin = "OnStartIngresoTrabajo",
                                    OnComplete = "OnComplete",
                                    OnFailure = "FailMessage",
                                    OnSuccess = "SuccessMessageIngresoTrabajo",
                                    UpdateTargetId = "dashboard"
                                }))
                                {
            @Html.AntiForgeryToken()
        <div class="portlet-body form">
            <div class="row">
                <div class="col-md-4">
                    <div class="form-group">
                        <label class="control-label col-md-3">Fecha Pago:</label>
                        <div class="col-md-9">
                            @Html.TextBoxFor(model => model.ExecutionDate, new { @class = "form-control form-control-inline date-picker", @type = "text", @placeholder = "dd/mm/aaaa", @readonly = true })
                            @Html.ValidationMessageFor(model => model.ExecutionDate, string.Empty, new { @class = "validate-error" })
                        </div>
                    </div>
                </div>
                <!--/span-->
                <div class="col-md-4">
                    <div class="form-group">
                        <label class="control-label col-md-3">Proveedor:</label>
                        <div class="col-md-9">
                            @Html.DropDownListFor(m => m.ddlProvider.SelectedItem, Model.ddlProvider.ListItems, new { @id = "ddlProvider", @size = 2, @readonly = true })
                        </div>
                    </div>
                </div>
                <!--/span-->
                <div class="col-md-3">
                    <div class="form-group">
                        <label class="control-label col-md-4">Nro Comprobante:</label>
                        <div class="col-md-8">
                            @Html.TextBoxFor(model => model.Receipt, new { @class = "form-control", @type = "number", @readonly = true })
                            @Html.ValidationMessageFor(model => model.Receipt, string.Empty, new { @class = "validate-error" })
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <div class="form-group">
                        <label class="control-label col-md-12">Comentario:</label>
                        <div class="col-md-12">
                            @Html.TextAreaFor(model => model.Commentary, new { @class = "form-control", @readonly = true })
                        </div>
                    </div>
                </div>
            </div>
            <!--/span-->
            <div class="row">
                <div class="col-md-3">
                    <div class="form-group">
                        <label class="control-label col-md-4">Sin Imputación:</label>
                        <div class="col-md-4">
                            @Html.CheckBoxFor(model => model.Advancement, new { @class = "form-control", @readonly = true })
                            @Html.ValidationMessageFor(model => model.Advancement)
                        </div>
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="form-group">
                        <label class="control-label col-md-4">Monto:</label>
                        <div class="col-md-8">
                            @Html.TextBoxFor(model => model.AdvancementAmount, new { @class = "form-control", @type = "number", @readonly = true })
                            @Html.ValidationMessageFor(model => model.AdvancementAmount, string.Empty, new { @class = "validate-error" })
                        </div>
                    </div>
                </div>
            </div>
            <br />
            <div class="row">
                <div class="col-md-6">
                    <!-- BEGIN Portlet PORTLET-->
                    <div class="portlet box blue-dark">
                        <div class="portlet-title">
                            <div class="caption">
                                <i class="fa fa-calculator"></i>Gastos
                            </div>
                        </div>
                        <div class="portlet-body">
                            <div id="paymentsTableDiv" style="position: relative; overflow: hidden; width: auto; min-height: 200px;">
                                <table id="paymentsTable" class="display table table-bordered table-striped table-condensed flip-content" style="overflow: hidden; white-space: nowrap; text-overflow: ellipsis;">
                                    <thead>
                                        <tr>
                                            <th style="display: none">Id</th>
                                            <th>Gasto</th>
                                            <th>Monto</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @foreach (var item in Model.Details)
                                        {
                                            <tr>
                                                <td style="display: none">@item.SpendingId</td>
                                                <td>@item.Spending</td>
                                                <td>@item.Total</td>
                                            </tr>
                                        }
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                    <!-- END Portlet PORTLET-->
                </div>
            </div>
            <br />
            <div class="row" id="divPM">
                <div class="col-md-6">
                    <!-- BEGIN Portlet PORTLET-->
                    <div class="portlet box blue-dark">
                        <div class="portlet-title">
                            <div class="caption">
                                <i class="fa fa-calculator"></i>Forma de Pago
                            </div>
                        </div>
                        <div class="portlet-body">
                            <div id="PaymentTableDiv" style="position: relative; overflow: hidden; width: auto; min-height: 200px;">
                                <table id="paymentsTable" class="display table table-bordered table-striped table-condensed flip-content" style="overflow: hidden; white-space: nowrap; text-overflow: ellipsis;">
                                    <thead>
                                        <tr>
                                            <th style="display: none">Id</th>
                                            <th>Forma de Pago</th>
                                            <th>Monto</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @foreach (var item in Model.PaymentMethods)
                                        {
                                            <tr>
                                                <td style="display: none">@item.PaymentMethodId</td>
                                                <td>@item.PaymentMethod</td>
                                                <td>@item.Amount</td>
                                            </tr>
                                        }
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                    <!-- END Portlet PORTLET-->
                </div>
            </div>            
            <div class="row">
                <div class="col-md-3">
                    <div class="form-group">
                        <label class="control-label col-md-4">Total:</label>
                        <div class="col-md-8">
                            @Html.TextBoxFor(model => model.Amount, new { @class = "form-control", @type = "number", @readonly = "readonly " })
                            @Html.ValidationMessageFor(model => model.Amount, string.Empty, new { @class = "validate-error" })
                        </div>
                    </div>
                </div>
            </div>
            <br />
            <div class="form-actions">
                <div class="row">
                    <div class="col-md-offset-5">
                        <a class="btn btn-primary" id="btnVolver">Volver</a>
                    </div>
                </div>
            </div>
        </div>
            }
        </div>
    </div>
</div>

<script type="text/javascript">
    $(document).ready(function () {


        $('#Advancement').iCheck({
            checkboxClass: 'icheckbox_square-grey',
            radioClass: 'iradio_square-grey',
            increaseArea: '20%' // optional
        });

        if ($("#ExpirationDate") == null || $("#ExpirationDate").val() === '') {
            $('#divPM').show();
            $('#divCurrentAccount').hide();
        }

        $("#CreateDate").datepicker();
        $("#NeedDate").datepicker();
        $('select').multiselect();      

        $('#btnVolver').click(function (event) {
            CallBackGet(function (data) {
                $("#dashboard").html(data);
            }, "/SallaryPayment/Index", null)
        });

    });
</script>