Multigroup.Portal/Controllers/Administration/SalaryAllocationController.cs
using Multigroup.Common.Logging;
using Multigroup.Portal.Filters;
using Multigroup.Portal.Models.Administration;
using Multigroup.Services.Shared;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Multigroup.Portal.Helpers;
using Multigroup.DomainModel.Shared;
using Multigroup.Portal.Providers;

namespace Multigroup.Portal.Controllers.Administration
{
    public class SalaryAllocationController : Controller
    {
        private SalaryAllocationService _salaryAllocationService;
        private IAuditLogHelper _auditLogHelper;
        private UserTypeService _userTypeService;
        private UserService _userService;
        private ProviderService _providerService;
        private PurchaseRequestService _purchaseRequestService;
        private ProfileProvider _profileProvider;

        public SalaryAllocationController()
        {
            _salaryAllocationService = new SalaryAllocationService();
            _auditLogHelper = new AuditLogHelper();
            _userTypeService = new UserTypeService();
            _userService = new UserService();
            _providerService = new ProviderService();
            _purchaseRequestService = new PurchaseRequestService();
            _profileProvider = new ProfileProvider();
        }

        // GET: /SalaryAllocation/
        [LogActionFilter]
        [Description("SalaryAllocations")]
        public ActionResult Index()
        {
            SalaryAllocationFilterVm model = new SalaryAllocationFilterVm();
            var collections = new CollectionHelper();
            model.ListProvider = new SelectList(_providerService.GetEmployeesWithId(), "ProviderId", "Name");
            model.ListUserAuth = new SelectList(_userService.GetUsersComplete(), "UserId", "Names");
            model.Authorized = true;
            return PartialView("~/Views/SalaryAllocation/SalaryAllocation.cshtml", model);
        }

        [LogActionFilter]
        [Description("SalarySettlement")]
        public ActionResult IndexSettlement()
        {
            SalaryAllocationFilterVm model = new SalaryAllocationFilterVm();
            var collections = new CollectionHelper();
            model.ListProvider = new SelectList(_providerService.GetEmployeesWithId(), "ProviderId", "Name");
            return PartialView("~/Views/SalaryAllocation/SalarySettlement.cshtml", model);
        }

        [LogActionFilter]
        [Description("SalarySettlement")]
        public ActionResult IndexGenerateSettlement()
        {
            SalaryAllocationFilterVm model = new SalaryAllocationFilterVm();
            var collections = new CollectionHelper();
            model.ListProvider = new SelectList(_providerService.GetEmployeesWithId(), "ProviderId", "Name");
            return PartialView("~/Views/SalaryAllocation/SalarySettlementCreate.cshtml", model);
        }

        public ActionResult GetTable(int? SelectedProvider, string DateFromStart, string DateToStart, string DateFromEnd, string DateToEnd, string AmountFrom, string AmountTo,  string isAuthorized, int? SelectedAuthorized)
        {
            var model = SalaryAllocationTableVm.ToViewModel(_salaryAllocationService.GetSalaryAllocationsSummary(SelectedProvider, DateFromStart, DateToStart, DateFromEnd, DateToEnd, AmountFrom,  AmountTo, isAuthorized, SelectedAuthorized));
            return PartialView("~/Views/SalaryAllocation/SalaryAllocationTable.cshtml", model);
        }

        public ActionResult GetTableSettlement(int? SelectedProvider, string Period)
        {
            var model = SalaryAllocationTableVm.ToViewModel(_salaryAllocationService.GetSalarySettlementSummary(SelectedProvider, Period));
            return PartialView("~/Views/SalaryAllocation/SalarySettlementTable.cshtml", model);
        }

        public ActionResult GetTableGenerateSettlement(string Period)
        {
            if (Period != "")
            { 
            var model = SalaryAllocationTableVm.ToViewModel(_salaryAllocationService.GetGenerateSalarySettlementSummary(Period));
            Session["SessionGenerateSettlement"] = model;
            Session["Period"] = Period;
            return PartialView("~/Views/SalaryAllocation/SalaryGenerateSettlementTable.cshtml", model);
            }
            else
                return new HttpStatusCodeResult(HttpStatusCode.InternalServerError, "Debe ingresar Periodo");
        }

        public ActionResult RemoveEmployee(int salaryAllocationId)
        {
            SalaryAllocationTableVm principal = (SalaryAllocationTableVm)Session["SessionGenerateSettlement"];
            IEnumerable<SalaryAllocationListVm> lista = (IEnumerable<SalaryAllocationListVm>)principal.SalaryAllocationList;
            List<SalaryAllocationListVm> list = lista.ToList();
            var item = list.FirstOrDefault(x => x.SalaryAllocationId == salaryAllocationId);
            list.Remove(item);

            principal.SalaryAllocationList = list;

            Session["SessionGenerateSettlement"] = principal;
            return PartialView("~/Views/SalaryAllocation/SalaryGenerateSettlementTable.cshtml", principal);
        }

        [LogActionFilter]
        [Description("Crear SalaryAllocations")]
        public ActionResult Create()
        {
            var model = new SalaryAllocationVm();
            var collections = new CollectionHelper();
            model.IsAuthorized = true;
            model.ddlProvider = collections.GetEmployeesIdsSingleSelectVm();
            model.ddlUserAuthorized = collections.GetUsersSingleSelectVm();
            return PartialView("~/Views/SalaryAllocation/SalaryAllocationCreate.cshtml", model);
        }

        public ActionResult ConfirmSalary(int id)
        {
            try
            {
                SalaryAllocation salary = _salaryAllocationService.GetSalaryAllocationsById(id);
                if (salary.UserAuthorizedId != _profileProvider.CurrentUserId)
                    ViewBag.ErrorMessageAuth = "true";
                else
                {
                    salary.IsAuthorized = true;
                    _salaryAllocationService.UpdateSalaryAllocation(salary);
                    ViewBag.ErrorMessageAuth = "false";                   
                }
                return Index();
            }
            catch (Exception ex)
            {
                return new HttpStatusCodeResult(HttpStatusCode.InternalServerError, "Error al Confirmar");
            }
        }

        [HttpPost]
        public ActionResult Create(SalaryAllocationVm model)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    var message = string.Join(" | ", ModelState.Values
                   .SelectMany(v => v.Errors)
                   .Select(e => e.ErrorMessage));

                    return new HttpStatusCodeResult(HttpStatusCode.InternalServerError, message);
                }
                var salaryAllocation = model.ToModelObject();

                if (salaryAllocation.EndDate.Date < salaryAllocation.StartDate.Date)
                    return new HttpStatusCodeResult(HttpStatusCode.InternalServerError, "La fecha de Inicio debe ser mayor a la fecha de Fin");

                    salaryAllocation.IsAuthorized = false;
                    _salaryAllocationService.AddSalaryAllocation(salaryAllocation);

                return Index();
            }
            catch (Exception ex)
            {

                return new HttpStatusCodeResult(HttpStatusCode.InternalServerError, "Se produjo un error al intentar guardar los datos.");
            }
        }

        public ActionResult GenerateSettlement(SalaryAllocationFilterVm filtro)
        {
            try
            {
                SalaryAllocationTableVm principal = (SalaryAllocationTableVm)Session["SessionGenerateSettlement"];
                IEnumerable<SalaryAllocationListVm> lista = (IEnumerable<SalaryAllocationListVm>)principal.SalaryAllocationList;
                List<Int32> ListaIds = new List<Int32>();
                foreach (SalaryAllocationListVm salary in lista)
                    ListaIds.Add(salary.SalaryAllocationId);
                    
                _salaryAllocationService.GenerateSettlement(ListaIds,(string)Session["Period"], _profileProvider.CurrentUserId, filtro.Description);
                lista = new List<SalaryAllocationListVm>();
                Session["SessionGenerateSettlement"] = lista;
                return IndexSettlement();
            }
            catch (Exception ex)
            {

                return new HttpStatusCodeResult(HttpStatusCode.InternalServerError, "Se produjo un error al intentar liquidar los sueldos.");
            }
        }

        public ActionResult View(int id)
        {
            var entity = _salaryAllocationService.GetSalaryAllocationsById(id);
            var model = SalaryAllocationVm.FromDomainModel(entity);
            var collections = new CollectionHelper();
            model.ddlProvider = collections.GetEmployeesIdsSingleSelectVm();
            model.ddlUserAuthorized = collections.GetUsersSingleSelectVm();
            model.ddlProvider.SelectedItem = entity.ProveedorId.ToString();
            model.ddlUserAuthorized.SelectedItem = entity.UserAuthorizedId.ToString();
            return PartialView("~/Views/SalaryAllocation/SalaryAllocationView.cshtml", model);
        }


        public ActionResult Edit(int id)
        {
            var entity = _salaryAllocationService.GetSalaryAllocationsById(id);
            var model = SalaryAllocationVm.FromDomainModel(entity);
            var collections = new CollectionHelper();          
            model.ddlUserAuthorized = collections.GetUsersSingleSelectVm();
            if (model.IsAuthorized)
                model.ddlProvider = collections.GetEmployeesByIdSingleSelectVm(entity.ProveedorId);
            else

Multigroup.Portal/Views/SalaryAllocation/SalaryAllocation.cshtml
<!-- VISTA: Maintenance/SalaryAllocation.cshtml -->
@model Multigroup.Portal.Models.Administration.SalaryAllocationFilterVm
<div class="clearfix">
</div>
<div class="row">
    <div class="col-md-12 column">
        <div class="portlet light bordered">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-SalaryAllocation"></i>
                    <span class="caption-subject bold uppercase">Imputación de Sueldo Fijo</span>
                </div>
                <div class="actions">
                    <a class="btn btn-default" id="btnAddSalaryAllocation">Añadir</a>
                    <div class="tooltipAai btn-group" id="idTooltipAai">
                        <a class="btn btn-default bootstro" id="btnViewSalaryAllocation" disabled="disabled">
                            Ver
                        </a>
                    </div>
                    <div class="tooltipAai btn-group" id="idTooltipAai">
                        <a class="btn btn-default bootstro" id="btnEditSalaryAllocation" disabled="disabled">
                            Editar
                        </a>
                    </div>
                    <a class="btn btn-default bootstro" id="btnAuthSalaryAllocation" disabled="disabled" data-toggle="modal" data-target="#authModal">
                        Autorizar
                    </a>
                    <a class="btn btn-icon-only btn-default fullscreen" href="javascript:;" data-original-title="" title="">
                    </a>
                </div>
            </div>
            <div class="portlet-body form">
                <div class="row">
                    <div class="col-md-3">
                        <div class="form-group">
                            <label class="control-label col-md-4">Fecha Inicio Desde:</label>
                            <div class="col-md-8">
                                <input type="text" class="form-control form-control-inline date-picker" id="txtDateFromStart" placeholder="dd/mm/aaaa" />
                            </div>
                        </div>
                    </div>
                    <div class="col-md-3">
                        <div class="form-group">
                            <label class="control-label col-md-4">Fecha Inicio Hasta:</label>
                            <div class="col-md-8">
                                <input type="text" class="form-control form-control-inline date-picker" id="txtDateToStart" placeholder="dd/mm/aaaa" />
                            </div>
                        </div>
                    </div>
                    <div class="col-md-3">
                        <div class="form-group">
                            <label class="control-label col-md-4">Usuario Autorizador:</label>
                            <div class="col-md-8">
                                @Html.DropDownListFor(m => m.SelectedUserAuth, Model.ListUserAuth, new { @size = "2" })
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-3">
                        <div class="form-group">
                            <label class="control-label col-md-4">Fecha Fin Desde:</label>
                            <div class="col-md-8">
                                <input type="text" class="form-control form-control-inline date-picker" id="txtDateFromEnd" placeholder="dd/mm/aaaa" />
                            </div>
                        </div>
                    </div>
                    <div class="col-md-3">
                        <div class="form-group">
                            <label class="control-label col-md-4">Fecha Fin Hasta:</label>
                            <div class="col-md-8">
                                <input type="text" class="form-control form-control-inline date-picker" id="txtDateToEnd" placeholder="dd/mm/aaaa" />
                            </div>
                        </div>
                    </div>
                    <div class="col-md-3">
                        <div class="form-group">
                            <label class="control-label col-md-4">Empleado:</label>
                            <div class="col-md-8">
                                @Html.DropDownListFor(m => m.SelectedProvider, Model.ListProvider, new { @size = "2" })
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-3">
                        <div class="form-group">
                            <label class="control-label col-md-4">Monto Desde:</label>
                            <div class="col-md-8">
                                @Html.TextBoxFor(model => model.AmounFrom, new { @class = "form-control", @type = "number", @Value = "" })
                            </div>
                        </div>
                    </div>
                    <div class="col-md-3">
                        <div class="form-group">
                            <label class="control-label col-md-4">Monto Hasta:</label>
                            <div class="col-md-8">
                                @Html.TextBoxFor(model => model.AmountTo, new { @class = "form-control", @type = "number", @Value = "" })
                            </div>
                        </div>
                    </div>
                    <div class="col-md-3">
                        <div class="form-group">
                            <label class="control-label col-md-4">Autorizado:</label>
                            <div class="col-md-8" id="sandbox-container">
                                @*<input type="checkbox" id="changePassword"/>*@
                                @Html.CheckBoxFor(model => model.Authorized, new { @id = "isAuthorized", @checked = true })
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row">                    
                    <div class="col-md-3">
                        <div class="form-group">
                            <div class="col-md-12">
                                <button id="btnBuscar" class="btn btn-default">Buscar</button>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12" id="acciones">

                    </div>
                </div>
            </div>
        </div>
        <div class="portlet portlet-sortable-empty">
        </div>
    </div>
</div>
<div class="modal fade" role="dialog" id="modalViewSalaryAllocation">

</div>
<div id="authModal" class="modal fade" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Autorizar Imputación de Sueldo</h4>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col-md-12">
                        <h3>¿Confirma que desea autorizar la Imputación de Sueldo?</h3>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal" id="authSalaryAllocationModalBtn">Confirmar</button>
                <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
            </div>
        </div>
    </div>
</div>
<!-- Note the missing multiple attribute! -->
<script type="text/javascript">
    $(document).ready(function () {

        var errorAuth = @ViewBag.ErrorMessageAuth
        $('#isAuthorized').iCheck({
            checkboxClass: 'icheckbox_square-grey',
            radioClass: 'iradio_square-grey',
            increaseArea: '20%' // optional
        });

        if (errorAuth == true) {
            Command: toastr["error"]("Usted no es el autorizante de esta Imputación de Sueldo")
            toastr.options = {
                "closeButton": true,
                "debug": false,
                "newestOnTop": false,
                "progressBar": false,
                "positionClass": "toast-top-center",
                "preventDuplicates": true,
                "onclick": null,
                "showDuration": "300",
                "hideDuration": "1000",
                "timeOut": "5000",
                "extendedTimeOut": "1000",
                "showEasing": "swing",
                "hideEasing": "linear",
                "showMethod": "fadeIn",
                "hideMethod": "fadeOut"
            }
        }


        $('.date-picker').datepicker();
        $('select').multiselect({
            includeSelectAllOption: true,
            enableFiltering: false,
        });
        $('.tooltipAai').tooltip({
            container: 'body',
            title: "Seleccione un gasto"
        });
        $('.tooltipSalaryAllocation1').tooltip({
            container: 'body',
            title: 'Seleccione un gasto'
        });
        $('#btnViewSalaryAllocation').click(function (event) {
            CallBackGet(function (data) {
                $("#dashboard").html(data);
            }, "/SalaryAllocation/View?id=" + id, null)
        });
        $('#btnEditSalaryAllocation').click(function (event) {
            CallBackGet(function (data) {
                $("#dashboard").html(data);
            }, "/SalaryAllocation/Edit?id=" + id, null)
        });

        $('#authSalaryAllocationModalBtn').click(function (event) {
            CallBackGet(function (data) {
                $("#dashboard").html(data);
            }, "/SalaryAllocation/ConfirmSalary?id=" + id, null)
        });

        $('#btnAddSalaryAllocation').click(function (event) {
            CallBackGet(function (data) {
                $("#dashboard").html(data);
            }, "/SalaryAllocation/Create", null)
        });



        $('#btnBuscar').click(function (event) {
            var params = {};
            params.SelectedProvider = $('#SelectedProvider').val();
            params.SelectedAuthorized = $('#SelectedUserAuth').val();
            params.AmountFrom = $('#AmounFrom').val();
            params.AmountTo = $('#AmountTo').val();
            params.DateFromStart = $('#txtDateFromStart').val();
            params.DateToStart = $('#txtDateToStart').val();
            params.DateFromEnd = $('#txtDateFromEnd').val();
            params.DateToEnd = $('#txtDateToEnd').val();
            if ($('#isAuthorized').is(':checked') == true) {
                params.isAuthorized = '1';
            } else {
                params.isAuthorized = '0';
            }
            CallBackGet(function (data) {
                $("#acciones").html(data);
            }, "/SalaryAllocation/GetTable", params)
        });

    });
</script>

Multigroup.Portal/Views/SalaryAllocation/SalaryAllocationCreate.cshtml
@model Multigroup.Portal.Models.Administration.SalaryAllocationVm
<div class="filter-container">
</div>

<div class="clearfix">
</div>
<div class="row">
    <div class="col-md-12 column">
        <div class="portlet light bordered">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-laptop"></i>
                    <span class="caption-subject bold uppercase">Ingresar Imputación de Sueldo</span>
                </div>              
                <div class="actions">
                    <a class="btn btn-icon-only btn-default fullscreen" href="javascript:;" data-original-title="" title="">
                    </a>
                </div>
            </div>
            @using (Ajax.BeginForm("Create", "SalaryAllocation", new AjaxOptions
            {
                HttpMethod = "POST",
                OnBegin = "OnStart",
                OnComplete = "OnComplete",
                OnFailure = "FailMessage",
                OnSuccess = "SuccessReturn"
            }))
            {
                @Html.AntiForgeryToken()
        <div class="portlet-body form">
            <div class="row">
                <div class="col-md-4">
                    <div class="form-group">
                        <label class="control-label col-md-3">Empleado:</label>
                        <div class="col-md-9">
                            @Html.DropDownListFor(m => m.ddlProvider.SelectedItem, Model.ddlProvider.ListItems, new { @id = "ddlProvider", @size = 2 })
                        </div>
                    </div>
                </div>
                <!--/span-->
                <div class="col-md-4">
                    <div class="form-group">
                        <label class="control-label col-md-3">Descripción:</label>
                        <div class="col-md-9">
                            @Html.TextBoxFor(model => model.Description, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.Description, string.Empty, new { @class = "validate-error" })
                        </div>
                    </div>
                </div>
                <!--/span-->
                <div class="col-md-4">
                    <div class="form-group">
                        <label class="col-md-3 control-label">Monto</label>
                        <div class="col-md-9">
                            @Html.TextBoxFor(model => model.Amount, new { @class = "form-control", @id = "Amount", @type = "number", @Value = "1" })
                            @Html.ValidationMessageFor(model => model.Amount, string.Empty, new { @class = "validate-error" })
                        </div>
                    </div>
                </div>
                <!--/span-->
            </div>
            <div class="row">
                <div class="col-md-4">
                    <div class="form-group">
                        <label class="control-label col-md-3">Fecha Inicio:</label>
                        <div class="col-md-9">
                            @Html.TextBoxFor(model => model.StartDate, new { @class = "form-control form-control-inline date-picker", @type = "text", @placeholder = "dd/mm/aaaa" })
                            @Html.ValidationMessageFor(model => model.StartDate, string.Empty, new { @class = "validate-error" })
                        </div>
                    </div>
                </div>
                <!--/span-->
                <div class="col-md-4">
                    <div class="form-group">
                        <label class="control-label col-md-3">Fecha Fin:</label>
                        <div class="col-md-9">
                            @Html.TextBoxFor(model => model.EndDate, new { @class = "form-control form-control-inline date-picker", @type = "text", @placeholder = "dd/mm/aaaa" })
                            @Html.ValidationMessageFor(model => model.EndDate, string.Empty, new { @class = "validate-error" })
                        </div>
                    </div>
                </div>
                <!--/span-->
                <div class="col-md-4">
                    <div class="form-group">
                        <label class="control-label col-md-3">Autoriza:</label>
                        <div class="col-md-8">
                            @Html.DropDownListFor(m => m.ddlUserAuthorized.SelectedItem, Model.ddlUserAuthorized.ListItems, new { @id = "ddlUserAuthorized", @size = 2 })
                        </div>
                    </div>
                </div>
                <!--/span-->
            </div>           
            <!--/span-->          
            <br />
            <div class="form-actions">
                <div class="row">
                    <div class="col-md-offset-5">
                        <button class="btn btn-primary" id="btnProcess">Guardar</button>
                    </div>
                </div>
            </div>
        </div>
                <div id="confirmModal" class="modal fade" data-backdrop-limit="1" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                    <div class="modal-dialog" role="document">
                        <div class="modal-content">
                            <div class="modal-header">
                                <button type="button" class="close" data-dismiss="modal" aria-label="Cerrar">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                                <h4 class="modal-title" id="myModalLabel">Guardar Imputación</h4>
                            </div>
                            <div class="modal-body">
                                <div class="row">
                                    <h3>¿Desea guardar la imputación de Sueldo?</h3>
                                </div>
                            </div>
                            <div class="modal-footer">
                                <button type="submit" id="btnProcess" class="btn btn-primary">Aceptar</button>
                                <button type="button" data-dismiss="modal" class="btn default">Cancel</button>
                            </div>
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
</div>

<script type="text/javascript">
    var user;
    var userAuthorized;
    $(document).ready(function () {

        $('select').multiselect();

        $("#StartDate").datepicker();

        $("#EndDate").datepicker();

    });

    function SuccessReturn() {
        CallBackGet(function (data) {
            $("#dashboard").html(data);
        }, "/SalaryAllocation/Index", null)
        SuccessMessage();
    }

</script>

Multigroup.Portal/Views/SalaryAllocation/SalarySettlement.cshtml
<!-- VISTA: Maintenance/SalarySettlement.cshtml -->
@model Multigroup.Portal.Models.Administration.SalaryAllocationFilterVm
<div class="clearfix">
</div>
<div class="row">
    <div class="col-md-12 column">
        <div class="portlet light bordered">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-SalarySettlement"></i>
                    <span class="caption-subject bold uppercase">Liquidación de Sueldos Fijos</span>
                </div>
                <div class="actions">
                    <a class="btn btn-default" id="btnAddSalarySettlement">Liquidar Sueldos</a>
                    <a class="btn btn-icon-only btn-default fullscreen" href="javascript:;" data-original-title="" title="">
                    </a>
                </div>
            </div>
            <div class="portlet-body form">
                <div class="row">
                    <div class="col-md-3">
                        <div class="form-group">
                            <label class="control-label col-md-4">Empleado:</label>
                            <div class="col-md-8">
                                @Html.DropDownListFor(m => m.SelectedProvider, Model.ListProvider, new { @size = "2" })
                            </div>
                        </div>
                    </div>
                    <div class="col-md-3">
                        <div class="form-group">
                            <label class="control-label col-md-4">Periodo:</label>
                            <div class="col-md-8">
                                @Html.TextBoxFor(model => model.Period, new { @class = "form-control", placeholder = "MM-DD" })
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row">                    
                    <div class="col-md-3">
                        <div class="form-group">
                            <div class="col-md-12">
                                <button id="btnBuscar" class="btn btn-default">Buscar</button>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12" id="acciones">

                    </div>
                </div>
            </div>
        </div>
        <div class="portlet portlet-sortable-empty">
        </div>
    </div>
</div>
<!-- Note the missing multiple attribute! -->
<script type="text/javascript">
    $(document).ready(function () {

        $('select').multiselect({
            includeSelectAllOption: true,
            enableFiltering: false,
        });
        $('.tooltipAai').tooltip({
            container: 'body',
            title: "Seleccione un gasto"
        });
        $('.tooltipSalarySettlement1').tooltip({
            container: 'body',
            title: 'Seleccione un gasto'
        });

        $('#btnAddSalarySettlement').click(function (event) {
            CallBackGet(function (data) {
                $("#dashboard").html(data);
            }, "/SalaryAllocation/IndexGenerateSettlement", null)
        });

        $('#btnBuscar').click(function (event) {
            var params = {};
            params.SelectedProvider = $('#SelectedProvider').val();
            params.Period = $('#Period').val();
            CallBackGet(function (data) {
                $("#acciones").html(data);
            }, "/SalaryAllocation/GetTableSettlement", params)
        });

    });
</script>